universe       = vanilla
getenv         = True
executable     = run.sh
arguments      = 0
initialdir     = /users/hiu-yeung.cheng/clusterlensing
request_cpus   = 8
request_memory = 8 GB

environment = "CSV=$ENV(HOME)/clusterlensing/oddratio/src_pos_tidy_v2.csv OUT_DIR=$ENV(HOME)/clusterlensing/out REQUEST_CPUS=$(request_cpus) DE_PROCS=$(request_cpus) MCMC_PROCS=$(request_cpus)"

output         = logs/row0.out
error          = logs/row0.err
log            = logs/job.log
queue 1